name: CI

on: [push, pull_request]

jobs:
  build:
    name: Poltergeist build ${{matrix.project}} (${{matrix.runtime}} ${{matrix.configuration}})
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [windows-latest]
        configuration: ['debug', 'release']
        project: ['Poltergeist.Editor', 'Poltergeist.Sandbox']
        include:
          - os: windows-latest
            runtime: 'win-x64'

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'

    - name: Restore dependencies
      run: dotnet restore -r ${{matrix.runtime}}

    - name: Build ${{matrix.project}}
      run: dotnet publish -c ${{matrix.configuration}} -r ${{matrix.runtime}} --no-restore ${{matrix.project}}

    - name: Upload ${{matrix.project}}
      uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.project}} (${{matrix.runtime}} ${{matrix.configuration}})
        path: ${{matrix.project}}/bin/${{matrix.configuration}}/net5.0/${{matrix.runtime}}/publish
